### ISSUE TITLE
Definir as informações que cada rota precisa e o que elas devem retornar

### ISSUE THREAD

**Issue by eduardor2m** [eduardor2m/task-manager#3]
**User** Routes

- [ ] SignUp (Cadastrar novo usuário)
- [ ] SignIn (Fazer login)

**Task** Routes

- [ ] Middleware Authenticate (Proteger rotas)
- [ ] CRUD (Tasks)
